# Generated by Django 2.0.13 on 2019-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0003_auto_20191224_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdivision',
            name='division_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5),
        ),
    ]
