# Generated by Django 2.0.13 on 2019-12-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0004_auto_20191224_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='mark_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
