# Generated by Django 2.0.13 on 2019-12-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0007_auto_20191230_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='availabile_divisions',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, null=True),
        ),
    ]
