# Generated by Django 2.0.13 on 2019-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0011_auto_20191230_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdivision',
            name='available_divisions',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='available_divisions',
            field=models.ManyToManyField(to='attendancebook.ClassDivision'),
        ),
    ]
