# Generated by Django 2.0.13 on 2019-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0012_auto_20191230_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='student_classname',
            field=models.CharField(max_length=100),
        ),
    ]
