# Generated by Django 2.0.13 on 2019-12-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0013_auto_20191230_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdivision',
            name='division_name',
            field=models.CharField(max_length=5),
        ),
    ]
