# Generated by Django 2.0.13 on 2019-12-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0014_auto_20191230_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='available_divisions',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_class',
        ),
        migrations.AddField(
            model_name='classdivision',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendancebook.StudentClass'),
        ),
        migrations.AlterField(
            model_name='classdivision',
            name='division_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='student_classname',
            field=models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendancebook.ClassDivision'),
        ),
    ]
