# Generated by Django 2.0.13 on 2019-12-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0015_auto_20191230_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendancebook.ClassDivision'),
        ),
    ]
