# Generated by Django 2.0.13 on 2019-12-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0016_auto_20191230_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classdivision',
            unique_together={('student_class', 'division_name')},
        ),
    ]
